---
- name: Ensure the boto is installed
  pip:
    name:
      - boto
      - boto3
    state: present

- name: ensure the dns record exist for ldap
  route53:
      state: present
      zone: "{{root_dns_hosted_zone}}"
      record: "{{krb_default_realm}}"
      type: A
      ttl: 7200
      value:
        - "{{ldap_host_ip}}"
      overwrite: yes
      wait: yes
      aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
      aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
